### ISSUE TITLE
seizure problem

### ISSUE THREAD

**Issue by GhostRock37** [pia-lab/pialab-docker#1]
Hello !

thank you for your job !

when I create a new PIA, I have a problem with the input fields: I can only enter one letter! in fact, the entry stops immediately and the field is validated ... I do not understand why?

**Comment by PapsOu** [comment]
Do you still have this issue ?

**Comment by GhostRock37** [comment]
yes sorry i have open a [new issu](https://github.com/pia-lab/pialab-docker/issues/3)  with a url and account for test it !
