### ISSUE TITLE
login problem with user on front 

### ISSUE THREAD

**Issue by GhostRock37** [pia-lab/pialab-docker#2]
Hello !

thank you for your job !

After performing the deployment without error, I was able to create a user on the back (with the user role only).

But, i can not log in with this user on the front! there is no message displayed: after entering the login / password, I stay on the login page!

you have an idea of ​​the problem ?

thank you

**Comment by GhostRock37** [comment]
It's seem to be a CORS probleme: i have this on the log => Cross-Origin Request Blocked : The same origin policy disallows reading the remote resource at http://localhost:8042/back/oauth/v2/token...

**Comment by PapsOu** [comment]
Hello @GhostRock37.

This repository is not stable enough. It has been created to test a typical PiaLab deployment.

You could try installing again the Docker container to fetch the latest master version.

But, master branch is not stable yet, so this is possible that you may encounter some problems again.

**Comment by GhostRock37** [comment]
Hello,

in fact by specifying the installation variables with the url of the service, I no longer had CORS concern.

thank you for your reply!

**Comment by PapsOu** [comment]
Yes these vars are used to set NelmioCorsBundle configuration.
