### ISSUE TITLE
issues for dpo validation

### ISSUE THREAD

**Issue by GhostRock37** [pia-lab/pialab-docker#4]
When the PIA is completed, the dpo can not give its final opinion and validate the PIA.

Once the PIA is completed and the different parts validated

1 - in the opinion DPO part, the DPO can not validate the PIA:

I can not check "the treatment can be implemented" => the box "The treatment should not be used." ticks all alone

2 - in the section "Concerned people opinion":

I can not check "Concerned people opinion was requested." => there too the box "Concerned people opinion was requested." ticks all alone

and ditto for the last field "The treatment could be implemented."
![validate_dpo](https://user-images.githubusercontent.com/25516319/41104314-5f96cae8-6a6b-11e8-9b0f-61754c49ca5e.JPG)

**Comment by RomainSanchez** [comment]
well spotted.thanks @GhostRock37 we'll look into that
Don't hesitate submitting a PR if you know how to fix an issue.
Contributions are very welcome

**Comment by RomainSanchez** [comment]
Please prefer https://github.com/pia-lab/pialab for non docker related issues in the future.thanks

**Comment by GhostRock37** [comment]
ok i will do ! thanks !

**Comment by RomainSanchez** [comment]
Fixed in https://github.com/pia-lab/pialab-back/commit/dea0578909aa1613f0204530d1bbead7f36a6cb2
