### ISSUE TITLE
 Installation error

### ISSUE THREAD

**Issue by GhostRock37** [pia-lab/pialab-docker#6]
HI !

when i try to run the install script, i have the error "**Command "pia:user:create" is not defined."**
see below ;

thx
```
bin/console pia:user:create lici@pialab.io pia42

 [WARNING] Some commands could not be registered:

In EnvVarProcessor.php line 77:

  Environment variable not found: "MAILER_SENDER".

Command "pia:user:create" is not defined.

  Did you mean one of these?
      doctrine:database:create
      doctrine:schema:create
      fos:oauth-server:create-client
      fos:user:activate
      fos:user:change-password
      fos:user:create
      fos:user:deactivate
      fos:user:demote
      fos:user:promote
      pia:application:create
      pia:structure:create
      pia:user:promote
      pia:user:remove


The command '/bin/sh -c git clone https://github.com/pia-lab/pialab-back.git -b ${BACKBRANCH} /usr/share/pialab-back     && cd /usr/share/pialab-back     && BUILDENV=${BUILDENV} Suffix=${NAME} CLIENTURL=${FRONTURL} ./bin/ci-scripts/set_env_with_etcd.sh     && ./bin/ci-scripts/set_pgpass.sh     && . /usr/share/pialab-back/.env     && ./bin/ci-scripts/install.sh     && ./bin/ci-scripts/create_database.sh     && psql -w -h ${DBHOST} -c "ALTER USER ${DBUSER} WITH PASSWORD '${DBPASSWORD}';" -U ${DBROOTUSER}     && ./bin/ci-scripts/create_schema.sh     && CLIENTURL=${FRONTURL} ./bin/ci-scripts/create_client_secret.sh     && if [ "$CREATEUSER" = "true" ]; then ./bin/ci-scripts/create_user.sh; fi     && ./bin/ci-scripts/update_users_app.sh     && ./bin/ci-scripts/post_install.sh' returned a non-zero code: 1
```

**Comment by PapsOu** [comment]
Hello @GhostRock37.

Your pasted stack display the following error : `Environment variable not found: "MAILER_SENDER".` that means that the env var `MAILER_SENDER` is missing.

This commit https://github.com/pia-lab/pialab-back/commit/46d1cd62f67b5b795aefb3d1a8a3eab47048d4d6 should fix your issue.

Please tell us if it's OK.

**Comment by GhostRock37** [comment]
Hi Papsou !

it's still KO (same error)!   

The variable is MAILER_SENDER (like in error msg) or  MailerSender (like in you [correction ](https://github.com/pia-lab/pialab-back/commit/46d1cd62f67b5b795aefb3d1a8a3eab47048d4d6) ?

**Comment by PapsOu** [comment]
Woops, I've missed only one line.

https://github.com/pia-lab/pialab-back/commit/6e1759fc7d9c25a131f6751d1b76e9792d7fa8a8

Please confirm the fix.

**Comment by GhostRock37** [comment]
tried 2 times, it's still KO (same errors:   Environment variable not found: "MAILER_SENDER" & Command "pia:user:create" is not defined. )!
